apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80    
      affinity:                                # We are using affinity to schedule pods on as specific node with the mentioned node labels and the condition 
        nodeAffinity:                                         
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
             matchExpressions:
              - key: color
                operator: In
                values:
                - blue
      
