apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: website-ingress
spec:
  rules:
  - host: website.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: default-service
            port:
              number: 80
      - path: /test
        pathType: Prefix
        backend:
          service:
            name: test-service
            port:
              number: 8000
  defaultBackend:
    service:
      name: backend-service
      port:
        number: 443