apiVersion: v1
kind: Pod
metadata:
  labels:
    run: pod
  name: mypod
  namespace: prod-namespace
spec:
  containers:
  - image: httpd
    name: mypodcont
    resources: 
       limits:
        memory: "1Gi"
        cpu: "1"
       requests:
        memory: "0.5Gi"
        cpu: "0.5"
  tolerations:
    - key: "Node.color"
      operator: "Equal"
      value: "red"
      effect: "NoSchedule"
  nodeSelector:
    name: gke-cluster-1-default-pool-30f35b31-rb2z
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
