apiVersion: v1
kind: ConfigMap
metadata:
  name: appdata_config
  labels:
    app: prod_app
data:
  APP_COLOR: blue
  APP_MODE: prod
  user-interface.properties: |
    color.good= purple
    color.bad= yellow