apiVersion: v1
kind: ConfigMap
metadata:
  name: appdata_config
  labels:
    app: prod_app
data:
  APP_COLOR: blue
  APP_MODE: prod
  user-interface.properties: |
    color.good= purple
    color.bad= yellow

---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
spec:
  containers:
  - name: nginx-container
    image: nginx
    
  restartPolicy: Always