apiVersion:
kind:
metatdata: 
    name: 
    labels: 
      app: 
    namespace:
spec:
  replicas:
  selector: 
    matchLabels:
      app: 
  template:
    metadata:
      labels:
        app: 
    spec:
      containers:
        - name: 
          image:
          ports:
            - containerPort:
    