apiVersion: v1
kind: Pod
metadata: 
    name: django-todo-pod
    namespace: django-todo-app
spec:
    containers:
    - name: django-todo-ctrl
      image: trainwitshubham/todo-app
      command: ["mkdir impAppFiles"]     #this is for adding a command to the pod file
      ports:
        - containerPort: 8001
         