apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  selector:
    app: mysql
  ports:
    - port: 3306
  clusterIP: None # Means no special ip wil be assigned to service it will use the
  # pods ip itself since there is only one pod and not multiple.