apiVersion: v1
kind: Service
metadata:
  name: usermgmt-restapp-service
  labels:
    app: usermgmt-restapp
spec:
  type: nodePort
  selector:
    app: usermgmt-restapp
  ports:
    - port: 8095
      targetPort: 8095
      nodePort: 31231
---
apiVersion: v1
kind: Service
metadata:
  name: usermgmt-restapp-CLB-service
  labels:
    app: usermgmt-restapp
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb    # To create Network Load Balancer
spec:
  type: LoadBalancer  # Default in AWS is Classic Load Blanacer, ut we have mentioned nlb in annotations.
  selector:
    app: usermgmt-restapp
  ports:
    - port: 80
      targetPort: 8095
---
apiVersion: v1
kind: Service
metadata:
  name: usermgmt-restapp-CLB-service
  labels:
    app: usermgmt-restapp
spec:
  type: LoadBalancer  # Default in AWS is Classic Load Blanacer
  selector:
    app: usermgmt-restapp
  ports:
    - port: 80
      targetPort: 8095
      