apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  type: ExternalName
  externalName: usermgmtdb.c7hldelt9xfp.us-east-1.rds.amazonaws.com

# For using this externalname service to connect to DB instaead of using the DB pod Some changes must be done to the
# App Pod manifest. THe DB Hostname in ENV should be chnaged to the name of this service, in this case it is the same
# as the db podname mysql. THe DB username and Password we used for connecting to DB must also be changed as per
# Configured in the RDS craeation