apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-sc
provisioner: ebs.csi.aws.com
#volumebindingmode will make sure that volume is binded only when a pod is provisioned and not before
volumeBindingMode: WaitForFirstConsumer
